spring.application.name=backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=pranavyuvarajr
spring.datasource.password=1234

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring Security
spring.security.user.name = admin
spring.security.user.password = admin